# settings.yaml
input_folder: "input"
index_file: "index.json"

embedding:
  model: "nomic-embed-text:latest"
  endpoint: "http://127.0.0.1:11434/api/embeddings"
  timeout: 15

llm:
  model: "llama3.2:latest"
  endpoint: "http://127.0.0.1:11434/v1/completions"
  temperature: 0.7
  max_tokens: 256
  timeout: 30
